sudo: required
language: java
services:
  - docker

before_install:
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh 
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - mvn test -B

deploy: 
  provider: script 
  script: 
    heroku container:push web --app auth-prodd;
    heroku container:release web --app auth-prodd;
  on: 
    branch: master
